# Generated by Django 2.1.3 on 2019-01-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job',
        ),
    ]
